# Configurações de produção para Billing Service
server:
  port: ${SERVER_PORT:8084}
  servlet:
    context-path: /billing
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  application:
    name: billing-service
  profiles:
    active: prod
  
  # Configuração do banco de dados
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:billing_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  # Configuração JPA
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  # Flyway para migração de banco
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true

# Configurações de logging para produção
logging:
  level:
    com.techbra.billing: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/billing-service/billing-service.log
    max-size: 100MB
    max-history: 30

# Configurações do Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: false

# Configurações específicas da aplicação
billing:
  payment:
    timeout: ${PAYMENT_TIMEOUT:60000}
    retry-attempts: ${PAYMENT_RETRY_ATTEMPTS:3}
    processor:
      url: ${PAYMENT_PROCESSOR_URL}
      api-key: ${PAYMENT_PROCESSOR_API_KEY}
  invoice:
    generation:
      enabled: true
      format: PDF
      storage:
        path: ${INVOICE_STORAGE_PATH:/var/billing/invoices}
  notification:
    email:
      enabled: true
      from: ${EMAIL_FROM:billing@techbra.com}
      smtp:
        host: ${SMTP_HOST}
        port: ${SMTP_PORT:587}
        username: ${SMTP_USERNAME}
        password: ${SMTP_PASSWORD}
        auth: true
        starttls: true
  integration:
    order-service:
      url: ${ORDER_SERVICE_URL:http://order-service:8083}
      timeout: ${ORDER_SERVICE_TIMEOUT:10000}
    customer-service:
      url: ${CUSTOMER_SERVICE_URL:http://customer-service:8081}
      timeout: ${CUSTOMER_SERVICE_TIMEOUT:10000}
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}

# Configurações de cache
cache:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000
    database: 0

# Configurações de monitoramento
monitoring:
  alerts:
    enabled: true
    webhook-url: ${ALERT_WEBHOOK_URL}
  metrics:
    custom:
      enabled: true