# TechBra Customer Service - Development Configuration
# Configuration for local development environment

spring:
  # H2 Database for development
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration

# Development logging
logging:
  level:
    com.techbra.customer: DEBUG
    org.springframework.security: DEBUG
    root: INFO

# Development specific settings
customer:
  registration:
    email-verification-required: false
    auto-activation: true
  
  password:
    min-length: 6
    require-uppercase: false
    require-lowercase: true
    require-numbers: false
    require-special-chars: false

# Management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh,env,configprops
  endpoint:
    health:
      show-details: always