# TechBra Customer Service - Default Configuration
# Microservice responsible for customer management and authentication

spring:
  application:
    name: customer-service
  
  # Database configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techbra_customers}
    username: ${DB_USERNAME:techbra_customer_admin}
    password: ${DB_PASSWORD:$=[1d"91Edzu}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Security configuration
  security:
    jwt:
      secret: ${JWT_SECRET:techbra-super-secret-key-for-jwt-tokens-2024}
      expiration: ${JWT_EXPIRATION:86400000} # 24 hours
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

server:
  port: 8081

# External service integrations
services:
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8086/api}
    timeout: ${NOTIFICATION_SERVICE_TIMEOUT:3000}
  
  config:
    url: ${CONFIG_SERVICE_URL:http://localhost:8888}

# Customer service specific configuration
customer:
  password:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-numbers: true
    require-special-chars: true
  
  registration:
    email-verification-required: true
    auto-activation: false
  
  profile:
    max-addresses: 5
    max-phone-numbers: 3

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      notification-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s

# Logging configuration
logging:
  level:
    com.techbra: INFO
    org.springframework.security: INFO
    root: INFO

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application info
info:
  app:
    name: ${spring.application.name}
    description: Customer Management and Authentication Service
    version: 1.0.0-SNAPSHOT
