# TechBra Product Catalog Service - Default Configuration
# Microservice responsible for product catalog management

spring:
  application:
    name: product-catalog-service
  
  # Database configuration
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techbra_products}
    username: ${DB_USERNAME:techbra_user}
    password: ${DB_PASSWORD:techbra_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis cache configuration
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: 8082

# External service integrations
services:
  inventory:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8087/api}
    timeout: ${INVENTORY_SERVICE_TIMEOUT:3000}
  
  config:
    url: ${CONFIG_SERVICE_URL:http://localhost:8888}

# Product catalog specific configuration
product:
  catalog:
    cache:
      ttl: 3600 # 1 hour in seconds
      max-size: 10000
    
    search:
      max-results: 100
      default-page-size: 20
    
    images:
      max-size: 5MB
      allowed-types: jpg,jpeg,png,webp
      base-url: ${IMAGES_BASE_URL:http://localhost:9000/images}
    
    categories:
      max-depth: 5
      cache-ttl: 7200 # 2 hours

# Circuit breaker configuration
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
  
  retry:
    instances:
      inventory-service:
        max-attempts: 3
        wait-duration: 500ms

# Cache configuration
spring:
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 1 hour in milliseconds
      cache-null-values: false

# Logging configuration
logging:
  level:
    com.techbra: INFO
    org.springframework.cache: DEBUG
    root: INFO

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,caches
  endpoint:
    health:
      show-details: always
    caches:
      enabled: true
  health:
    redis:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Application info
info:
  app:
    name: ${spring.application.name}
    description: Product Catalog Management Service
    version: 1.0.0-SNAPSHOT
  features:
    - "Product catalog management"
    - "Category hierarchy"
    - "Redis caching"
    - "Image management"
    - "Search functionality"