services:
  bff-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bff-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://techbra-config-service:8888
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-admin:config-secret@techbra-config-service:8888
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - techbra-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  techbra-network:
    driver: bridge
    external: true

volumes:
  bff-logs:
    driver: local