# Logistics Service - Bootstrap Configuration
# All configurations are now managed by Spring Cloud Config Server
# This file contains only bootstrap configurations needed to connect to config server

spring:
  application:
    name: logistics-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "configserver:http://config-admin:config-secret@${CONFIG_SERVER_URL:localhost:8888}"

# Fallback server port (can be overridden by config server)
server:
  port: ${SERVER_PORT:8082}