# Logistics Service - Bootstrap Configuration
spring:
  application:
    name: logistics-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Fallback server port
server:
  port: ${SERVER_PORT:8082}