# Customer Service - Local Configuration
# Most configurations are now managed by Spring Cloud Config Server
# This file contains only local overrides and fallback configurations

spring:
  application:
    name: order-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://config-admin:config-secret@localhost:8888}

# Fallback server port (can be overridden by config server)
server:
  port: 8083

# Local management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:
    health:
      show-details: when-authorized