# TechBra Config Service Configuration
# Centralized configuration server for microservices platform

server:
  port: 8888
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: config-service
  
  profiles:
    active: native
  
  cloud:
    config:
      server:
        # Native profile - file system based configuration
        native:
          search-locations: classpath:/config-repo/
        # Security for configuration access
        encrypt:
          enabled: false
        # Health indicator disabled for Git repository
        health:
          enabled: false
  
  # Security configuration
  security:
    user:
      name: ${CONFIG_USERNAME:config-admin}
      password: ${CONFIG_PASSWORD:config-secret}
      roles: ADMIN

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    refresh:
      enabled: true
  health:
    diskspace:
      enabled: true
    ping:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms

# Logging configuration
logging:
  level:
    com.techbra: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%logger{36}] - %msg%n"
  file:
    name: logs/config-service.log
    max-size: 10MB
    max-history: 30

# Application info
info:
  app:
    name: ${spring.application.name}
    description: TechBra Centralized Configuration Server
    version: 1.0.0-SNAPSHOT
    encoding: UTF-8
    java:
      version: ${java.version}
  build:
    artifact: ${project.artifactId:config-service}
    name: ${project.name:TechBra Config Service}
    description: ${project.description:Centralized configuration server for TechBra microservices platform}
    version: ${project.version:1.0.0-SNAPSHOT}
  git:
    branch: ${git.branch:unknown}
    commit:
      id: ${git.commit.id:unknown}
      time: ${git.commit.time:unknown}

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/,file:./config-repo/

logging:
  level:
    com.techbra: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.security: DEBUG
    root: DEBUG

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo-test/

logging:
  level:
    com.techbra: INFO
    org.springframework.cloud.config: INFO
    root: WARN

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI}
          username: ${CONFIG_GIT_USERNAME}
          password: ${CONFIG_GIT_PASSWORD}
          clone-on-start: true
          force-pull: true
        encrypt:
          enabled: true
          key: ${CONFIG_ENCRYPT_KEY}

logging:
  level:
    com.techbra: INFO
    org.springframework.cloud.config: INFO
    org.springframework.security: WARN
    root: WARN
  file:
    name: /var/log/config-service/config-service.log

management:
  endpoint:
    health:
      show-details: when-authorized