services:
  billing-postgres:
    image: postgres:17
    container_name: billing-postgres
    environment:
      POSTGRES_DB: techbra_billings
      POSTGRES_USER: techbra_billing_admin
      POSTGRES_PASSWORD: $=[1d"91Edzu
    ports:
      - "5436:5432"
    restart: unless-stopped
    networks:
      - billing-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techbra_billing_admin -d techbra_billings"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_billing_data:
    driver: local

networks:
  billing-network:
    driver: bridge
  techbra-network:
    external: true
    driver: bridge