version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: customer_postgres
    environment:
      POSTGRES_DB: techbra_customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $=[1d"91Edzu
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - customer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  customer-service:
    build: .
    container_name: customer_service
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - customer-network
    restart: unless-stopped

networks:
  customer-network:
    driver: bridge