services:
  customer-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer-service:latest
    container_name: customer-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://host.docker.internal:8888
    depends_on:
      customer-postgres:
        condition: service_healthy
    networks:
      - customer-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  customer-postgres:
    image: postgres:17
    container_name: customer-postgres
    environment:
      POSTGRES_DB: techbra_customers
      POSTGRES_USER: techbra_customer_admin
      POSTGRES_PASSWORD: $=[1d"91Edzu
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - customer-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techbra_customer_admin -d techbra_customers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_customer_data:
    driver: local

networks:
  customer-network:
    driver: bridge